Repository bounswe/bounswe2022group6, pull requests merged in 2023-01, with the labels that each got.

#462 Standards Part Added
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: Medium, State: Completed

#463 Annotations Part Added
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: Medium, State: Completed

#465 User Scenarios and Mockups
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#467 UML diagrams added
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#466 Added Yusuf Erdem Nacar's Individual Report and Effort Table
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: Medium, State: Completed

#470 API Endpoints are updated
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High

#474 Final Milestone Report: Added UI screenshots and my own part
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation

#473 Work Performed & Individual Report - Hakan BALIK
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#468 UI / UX of Frontend
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#476 Final Milestone Report
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High

#475 Software Requirement Specification Added.
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#477 Added Backend Tests to the Unit Tests Section
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#478 Executive Summary Part Added
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High, State: Completed

#487 General/documentation/artun akdogan indıvıdual report
  deliverables/CMPE451_Customer_Presentation_Milestone_3.md
Labels: Type: Documentation, Priority: High
